title: alfredtm
description: Personal blog by Alfred
url: "https://alfredtm.github.io"
baseurl: ""

markdown: kramdown
permalink: /:year/:month/:day/:title/

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
